# Generated by Django 6.0.1 on 2026-01-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_producttype_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('accepted', 'Принят в работу'), ('ready', 'Готов')], default='processing', max_length=20),
        ),
    ]
